### ISSUE TITLE
StudentBunks Authentication(frontend)

### ISSUE THREAD

**Issue by isrealOparanti6542** [isrealOparanti6542/StudentBunks#2]
A page will be created for a user to choose an option, whether to log in as a Student or a business owner, then link will redirect to prospective route. 
Assigned in the previous meeting to @Walter-Tronics

**Comment by Walter-Tronics** [comment]
I am done creating the pages for signing up a user. The initial signup page for navigating the user base on his/her interest and also the respective page.

The pull-request is attached to this issue.
